application: neuronism2
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:

# CSS
- url: /css
  static_dir: css

# HTML
- url: /static
  static_dir: static_html

- url: /neuron
  static_dir: website/generated

#- url: /admin/get_ss.*
#  script: admin_get_ss.py
#  login: admin

- url: /admin/continue_batch.*
  script: admin_continue_batch.py
  login: admin

- url: /admin/report.*
  script: main.py
  login: admin

- url: /admin.*
  script: admin.py
  login: admin

- url: /.*
  script: main.py
  login: required


libraries:

- name: webapp2
  version: latest

- name: jinja2
  version: latest
